blockbuster/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^bookfinder/', include('bookfinder.urls', namespace="bookfinder")),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace="auth")),
]

bookfinder/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^recommendation/$', views.user_recommendation_list, name='user_recommendation_list'),
]

bookfinder/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
import numpy as np

class Book(models.Model):
    gid = models.CharField(max_length = 200, unique = True, default = 'NA')
    title = models.CharField(max_length = 200, default = 'NA')
    author = models.CharField(max_length = 50, default = 'NA')
    url = models.URLField(default = 'NA')
    description = models.CharField(max_length = 5000, default = 'NA')

    def average_rating(self):
        all_ratings = map(lambda x: x.rating, self.review_set.all())
        return np.mean(all_ratings)

    def __unicode__(self):
        return self.title

class Rating(models.Model):
    book = models.ForeignKey(Book)
    user_name = models.CharField(max_length=100)
    rating = models.FloatField(validators = [MinValueValidator(0.0), MaxValueValidator(10.0)])
    class Meta:
        unique_together = ('book', 'user_name')

class Cluster(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def get_members(self):
        return "\n".join([u.username for u in self.users.all()])

bookfinder/forms.py
from django import forms

class IdeaForm(forms.Form):
    idea = forms.CharField(widget=forms.Textarea(attrs={'cols': 40, 'rows': 10}))

bookfinder/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import IdeaForm
from .models import Rating, Book, Cluster
from django.contrib.auth.models import User
from .suggestions import update_clusters
from gensim.summarization import keywords
import datetime
import requests
import json
from django.db import transaction

def add_book(volume, user_name):
    book, createdbook = Book.objects.get_or_create(
        gid = volume['id'],
    )
    book.title = volume['title'],
    book.author = volume['author'],
    book.description = volume['description'],
    book.url = volume['url']
    rating, createdbook = Rating.objects.get_or_create(
        book = book,
        user_name = user_name,
        rating = 1.0
    )
    with transaction.atomic():
        if createdbook == True:
            book.save()
        rating.save()

def make_api_call(payload):
    URL = 'https://www.googleapis.com/books/v1/volumes?q='
    for i in payload:
        URL += i + ','
    URL = URL[:-1]
    print URL
    r = json.loads(requests.get(URL).text)
    return r

@login_required
def home(request):
    form = IdeaForm()
    user_name = request.user.username
    book_list = []
    if request.method == 'POST':
        form = IdeaForm(request.POST)
        inp = request.POST.get('idea')
        try:
            words = keywords(inp)
        except Exception:
            return render(request, 'bookfinder/home.html', {'form': form, 'error': 'Please type more.'})
        if len(words) != 0:
            books = make_api_call(str(words).split('\n'))
            for book in books['items']:
                volume = {}
                volume['title'] = book['volumeInfo']['title']
                volume['id'] = book['id']
                volume['url'] = book['volumeInfo']['infoLink']
                try:
                    volume['description'] = book['volumeInfo']['description']
                except KeyError:
                    volume['description'] = 'Not available'
                try:
                    volume['author'] = book['volumeInfo']['authors'][0]
                except KeyError:
                    volume['author'] = 'Not Available'
                book_list.append(volume)
                add_book(volume, user_name)
                update_clusters()
            return render(request, 'bookfinder/home.html', {'form': form, 'book_list': book_list})
        else:
            return render(request, 'bookfinder/home.html', {'form': form, 'error': 'Please type more.'})
    return render(request, 'bookfinder/home.html', {'form': form})

@login_required
def user_recommendation_list(request):
    user_ratings = Rating.objects.filter(user_name=request.user.username).prefetch_related('book')
    user_ratings_book_ids = set(map(lambda x: x.book.id, user_ratings))
    try:
        user_cluster_name = User.objects.get(username=request.user.username).cluster_set.first().name
    except:
        update_clusters()
        user_cluster_name = User.objects.get(username=request.user.username).cluster_set.first().name

    user_cluster_other_members = \
        Cluster.objects.get(name=user_cluster_name).users \
            .exclude(username=request.user.username).all()
    other_members_usernames = set(map(lambda x: x.username, user_cluster_other_members))

    other_users_ratings = \
        Rating.objects.filter(user_name__in=other_members_usernames) \
            .exclude(book__id__in=user_ratings_book_ids)
    other_users_ratings_book_ids = set(map(lambda x: x.book.id, other_users_ratings))

    book_list = list(Book.objects.filter(id__in=other_users_ratings_book_ids))
    for i in book_list:
        if i.title[0] == '(':
            i.title = i.title[3:-3]
        if i.author[2] == 'N':
            i.author = i.author[2:-3]
        else:
            i.author = i.author[3: -3]
        if i.description[2] == 'N':
            i.description = i.description[2:-3]
        else:
            i.description = i.description[3:-3]

    return render(
        request,
        'bookfinder/user_recommendation_list.html',
        {'username': request.user.username, 'book_list': book_list})

bookfinder/templates/bookfinder/home.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}
  <h2>Book Finder</h2>
{% endblock %}

{% block content %}
  <form action="" method="POST" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Get Books
      </button>
      {% endbuttons %}
  </form>
  {% if book_list %}
  <div class="row">
      {% for book in book_list %}
      <div class="col-xs-6 col-lg-4">
          <h4><a href="{{ book.url }}">
          {{ book.title | truncatewords:4}}
          </a></h4>
          <h6>{{ book.author }}</h6>
          <p>{{ book.description|truncatewords:20 }}</p>
      </div>
      {% endfor %}
  </div>
  {% else %}
    {% if error %}
      <p style="color: red">
        Please type more!
      </p>
    {% endif %}
    <p>Please type in your idea</p>
  {% endif %}
{% endblock %}

bookfinder/templates/bookfinder/user_recommendation_list.html
{% extends 'base.html' %}

{% block title %}
<h2>Recommendations for {{ username }}</h2>
{% endblock %}

{% block content %}
{% if book_list %}
<div class="row">
    {% for book in book_list %}
    <div class="col-md-6">
        <h4>
        {{ book.title }}
        </h4>
        <h6>{{ book.author }}</h6>
        <p>{{ book.description | truncatewords:60 }}</p>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No book suggestions available.</p>
{% endif %}
{% endblock %}

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'bookfinder:home' %}">Blockbuster</a>
  </div>
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li><a>Hello {{ user.username }}</a></li>
      <li><a href="{% url 'bookfinder:user_recommendation_list' %}">Book suggestions</a></li>
      <li><a href="{% url 'auth:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'auth:login' %}">Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
<div class="container">
    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}